export const ActionTypes = {
  FETCH_IMAGES: "FETCH_IMAGES",
  CHANGE_QRY: "CHANGE_QRY",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  SELECT_IMG: "SELECT_IMG",
  SET_COLS: "SET_COLS",
  NEXT_PAGE: "NEXT_PAGE",
  PREV_PAGE: "PREV_PAGE",
};
